NumPy is a Python library.
NumPy is used for working with arrays.
NumPy is short for "Numerical Python".

In [1]:
import numpy
arr=numpy.array([1,4,6,3,6])
print(arr)

[1 4 6 3 6]


In [2]:
import numpy as np
arr=np.array([1,4,6,3,6])
print(arr)

[1 4 6 3 6]


In [3]:
import numpy as np
print(np.__version__)

1.26.2


In [4]:
import numpy as np
arr=np.array([1,4,6,3,6])
print(arr)
print(type(arr))

[1 4 6 3 6]
<class 'numpy.ndarray'>


In [5]:
# 0 D array
import numpy as np
arr=np.array(26)
print(arr)

26


In [8]:
# 1D array
import numpy as np
arr=np.array([1,4,2])
arr

array([1, 4, 2])

In [13]:
# 2D array
import numpy as np
arr=np.array([[1,4,2],[5,7,5]])
print(arr)

[[1 4 2]
 [5 7 5]]


In [15]:
# 3D array
import numpy as np
arr=np.array([[[1,4,2],[5,7,5]],[[1,5,9],[6,9,3]]])
print(arr)

[[[1 4 2]
  [5 7 5]]

 [[1 5 9]
  [6 9 3]]]


In [16]:
#check number of dimensions
import numpy as np
a=np.array(26)
b=np.array([1,4,2])
c=np.array([[1,4,2],[5,7,5]])
d=np.array([[[1,4,2],[5,7,5]],[[1,5,9],[6,9,3]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
#Higher dimensional array
import numpy as np
arr=np.array([3,5,2,1],ndmin=7)
print(arr)
print("Number of dimensions:",arr.ndim)

[[[[[[[3 5 2 1]]]]]]]
Number of dimensions: 7


In [19]:
#access array elements
import numpy as np
arr=np.array([1,4,6,3,6])
print(arr[1])

4


In [22]:
#get third and fifth elements from array and add them
import numpy as np
arr=np.array([1,5,3,1,6,8])
print(arr[2]+arr[4])

9


In [23]:
#access 2D arrays
import numpy as np
arr=np.array([[1,3,5,8,3,6],[8,9,3,2,1,5]])
print("Fifth element on second row:",arr[1][4])

Fifth element on second row: 1


In [28]:
#access 3D arrays
#access third element of second array of the first array
import numpy as np
arr=np.array([[[2,8,4,9,1],[1,7,7,9,2]],[[1,2,3,4,5],[9,8,6,4,1]]])
print(arr[0][1][2])

7


In [1]:
#negative indexing
#print last element from second dimension
import numpy as np
arr=np.array([[1,3,5,8,3,6],[8,9,3,2,1,5]])
print("Last element of second dimension:",arr[1,-1])

Last element of second dimension: 5


In [2]:
#slicing arrays
import numpy as np
arr=np.array([1,3,5,2,5,6,2,8])
print(arr[1:5])

[3 5 2 5]


In [3]:
#slice elements from index 4 to the end of array
import numpy as np
arr=np.array([1,3,5,2,5,6,2,8])
print(arr[4:])

[5 6 2 8]


In [4]:
#slice elements from beginning to the index 5(not included)
import numpy as np
arr=np.array([1,3,5,2,5,6,2,8])
print(arr[:5])

[1 3 5 2 5]


In [5]:
#negative slicing
#slice from the index 3 from the end to index 1 from the end
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [6]:
#Use the step value to determine step of slicing
#Return every other element from index 1 to index 5
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [7]:
#return every other element
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [8]:
#slicing 2D arrays
#from the second element,slice elements from index 1 to index 4(not included)
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [9]:
#from both elements, return index 2
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [10]:
#from both elements, slice index 1 to index 4, this will return a 2D array
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [13]:
#checking the data type of array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [14]:
#get the data type of array containing strings
import numpy as np
arr=np.array(["BMW","Fortuner","Thar"])
print(arr.dtype)

<U8


In [15]:
#create an array with data type string
import numpy as np
arr=np.array([1,2,3,4],dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [16]:
#create an array with data type 4 byte integer
import numpy as np
arr=np.array([1,2,3,4],dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [17]:
#change the data type from float to integer by using 'i' as parameter value
import numpy as np
arr=np.array([1.1,2.3,4.5])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 4]
int32


In [18]:
#change data type from integer to boolean
import numpy as np
arr=np.array([1,2,3,4])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True  True]
bool


In [19]:
#make a copy,change the original array,display both arrays
import numpy as np
arr=np.array([1,2,3,4])
x=arr.copy()
arr[0]=16
print(arr)
print(x)

[16  2  3  4]
[1 2 3 4]


In [20]:
#make a view,change the original array,display both arrays
import numpy as np
arr=np.array([1,2,3,4])
x=arr.view()
arr[0]=16
print(arr)
print(x)

[16  2  3  4]
[16  2  3  4]


In [1]:
#make a view,change the view,display both arrays
import numpy as np
arr=np.array([1,2,3,4])
x=arr.view()
arr[0]=82
print(arr)
print(x)

[82  2  3  4]
[82  2  3  4]


In [1]:
#print the value of base attribute to check if an array owns it's data or not
import numpy as np
arr=np.array([1,2,3,4])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4]


In [5]:
#print the shape of 2D array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [6]:
#reshape from 1d to 2D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
#reshape from 1D to 3D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
#unknown dimension
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#flattening the array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [10]:
#iterate on the elements of the following 1D array
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [11]:
#iterate on the elements of the following 2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [12]:
#iterate on each scalar element of the following 2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)
    

1
2
3
4
5
6


In [13]:
#iterate on the elements of the following 3D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [14]:
#iterate on each scalar element of the following 2D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
#iterate using nditer
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
#iterate through the array as a string
import numpy as np
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [17]:
#enumerate on the following 1D array elements
import numpy as np
arr=np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [18]:
#enumerate on the following 1D array elements
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [19]:
#join two arrays
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [20]:
#join two 2D arrays along rows(axis=1)
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[6,7]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 4 5]
 [3 4 6 7]]


In [2]:
#joining arrays using stack functions
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)
print(arr.ndim)

[[1 4]
 [2 5]
 [3 6]]
2


In [3]:
#stacking along rows
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [4]:
#stacking along columns
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [5]:
#stacking along height (depth)
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[[1 4]
  [2 5]
  [3 6]]]
3


In [8]:
#splitting numpy arrays
#split the array in 3 parts
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [9]:
#access the splitted arrays
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2 3]
[4 5 6]
[7 8]


In [11]:
#split the 2D array into three 2D arrays
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [12]:
#split the 2D array into three 2D arrays along rows
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [16]:
#use hsplit()method to split 2D array into three 2D arrays along rows
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.hsplit(arr,2)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [17]:
#searching arrays
#find the indexes where the value is 4
import numpy as np
arr=np.array([1,3,5,4,7,8,4,6,4])
x=np.where(arr==4)
print(x)

(array([3, 6, 8], dtype=int64),)


In [18]:
#find the indexes where the values are even
import numpy as np
arr=np.array([1,3,5,4,7,8,4,6,4])
x=np.where(arr%2==0)
print(x)

(array([3, 5, 6, 7, 8], dtype=int64),)


In [22]:
#Find the indexes where the value 7 would be inserted
import numpy as np
arr=np.array([1,3,7,5,4,7,8,4,6,4,7])
x=np.searchsorted(arr,7)
print(x)

2


In [27]:
#Find the indexes where the value 6 would be inserted,starting from the right side
import numpy as np
arr=np.array([1,3,7,5,4,7,8,4,6,4])
x=np.searchsorted(arr,6,side='right')
print(x)

2


In [26]:
#find the indexes where the values 2,4,6 should be inserted
import numpy as np
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


In [28]:
#sort the array
import numpy as np
arr=np.array([4,2,3,1])
print(np.sort(arr))

[1 2 3 4]


In [29]:
#sort the array alphabetically
import numpy as np
arr=np.array(['Thar','BMW','Fortuner','WagonR'])
print(np.sort(arr))

['BMW' 'Fortuner' 'Thar' 'WagonR']


In [30]:
#sort a boolean array
import numpy as np
arr=np.array([True,False,True,False,False,True])
print(np.sort(arr))

[False False False  True  True  True]


In [31]:
#sort a 2D array
import numpy as np
arr=np.array([[7,1,4],[4,1,0]])
print(np.sort(arr))

[[1 4 7]
 [0 1 4]]


In [1]:
#filtering arrays
#create an array from the elements on index 0 and 2:
import numpy as np
arr=np.array([4,2,3,1])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[4 3]


In [3]:
#create a filter array that will return only values greater than 42
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)    

[False, False, True, True]
[43 44]


In [4]:
#create a filter array that will return only even numbers from the original array
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if element%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)
        

[False, True, False, True]
[42 44]


In [5]:
#create a filter array that will return only values higher than 42
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [6]:
#create a filter array that will return only even elements from original array
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]
